Fix formatting and parsing changes
osowskit/letsencrypt-dnsimple-hook pull request #12
Opened 2017-03-26 20:57 UTC by osowskit

* Switch indentation back to two spaces
* Switch `verify_record` to use the function parameter `challenge`
* Switch `PublicSuffix` to use `parse` instead of `domain`

2017-03-27 01:49 UTC, jbjonesjr requested changes
just minor optimizations suggested, rest of the code looks SOLID. I found the parse and challenge  bugs myself (and pushed them to the main branch before i saw this :( )

2017-03-27 01:49 UTC, jbjonesjr commented on dnsimple_hook.rb
> +    if dns_simple_domain_name.eql? domain_name
why assign just to use in only once in the next line. While maybe a bit more readable, i don't think it's worth it.

2017-03-27 01:49 UTC, jbjonesjr commented on dnsimple_hook.rb
> +      found_record = true
maybe change this to `return true` so we can short-circuit future iterations of the loop?

2017-03-27 01:49 UTC, jbjonesjr commented on dnsimple_hook.rb
> +  return found_record
this can be `return false` since we short circuited above

2017-03-27 01:49 UTC, jbjonesjr commented on dnsimple_hook.rb
> +  return found_record
**NOTE:** With these changes, we can :fire: the `found_record` attribute

2017-03-27 01:50 UTC, jbjonesjr commented
Feel free to ignore my changes though, they are more preference pieces, not problems

2017-03-27 02:23 UTC, osowskit commented on dnsimple_hook.rb
> +      found_record = true
Agreed ❤️. Updated.

2017-03-27 02:23 UTC, osowskit commented on dnsimple_hook.rb
> +  return found_record
Done.

2017-03-27 14:35 UTC, jbjonesjr approved these changes

2017-03-27 14:36 UTC, jbjonesjr commented
Approving, not sure if you want to do anything with the domain_name variables and such (they seem a bit overloaded).

Instead of my suggestion from last night, we may be better off giving `domain_name` a more descriptive name to start with

2017-04-01 02:45 UTC, jbjonesjr commented
Think we should merge and consider this an MVP.

2017-04-01 14:01 UTC, osowskit commented
Sure thing. Thanks for the reviews

2017-04-01 14:02 UTC, merged